create database customer_behaviour;

use customer_behaviour;

#1. total revenue generated by male vs female customers

select gender,sum(purchase_amount) as 'total revenue' from customer
group by gender ;

#2. Which customers used a discount but still spends more than average purchase amount 

select * from customer
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer) ;

#3. Which are the top 5 products with the highest  average review rating

select item_purchased , round(avg(review_rating),2) as 'Avg rating' from customer
group by item_purchased 
order by avg(review_rating) desc
limit 5;

#4. comparing standard and express shipping methods average purchase amounts

select shipping_type , round(avg(purchase_amount),2) from customer
where shipping_type in ('Express','Standard')
group by shipping_type;

#5. Do subscribed customeres spend more

select subscription_status ,count(customer_id) as no_ofcustomers, round(avg(purchase_amount),2) as avg_amount , round(sum(purchase_amount),2) 
 as total_revenue from customer
group by subscription_status;

#6. -- Products with highest average spend when discounted

select item_purchased , round(avg(purchase_amount),2) as avg_amount from customer
where discount_applied = 'Yes'
group by item_purchased
order by round(avg(purchase_amount),2) desc
limit 5;

#7.  Segment customers into New , Returning , and loyal based on their total number of previous purchases ,  and show count of each segment 

select count(customer_id) as no_of_customers , purchase_frequency_group from customer
group by purchase_frequency_group;

#. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

#9. Which age group contributes the most revenue, and should the company focus marketing efforts on that segment?

SELECT
    age_group,
    COUNT(*) AS total_orders,
    ROUND(SUM(purchase_amount),2) AS total_revenue,
    ROUND(AVG(purchase_amount),2) AS avg_order_value
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

#insight .Adults generate the highest revenue and should be the primary target for marketing campaigns and product promotions.

#10. Is the subscription program actually increasing customer value?

SELECT
    subscription_status,
    COUNT(*) AS customers,
    ROUND(AVG(purchase_amount),2) AS avg_purchase_amount,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status;

#insight , Subscribers spend 35% more per order than non-subscribers, indicating that the subscription program positively impacts customer spending.